### ISSUE TITLE
DMCA Violation

### ISSUE THREAD

**Issue by Minesraft2** [TrollAndHack/blooket-hacks-for-SWMS#1]
This repository is a reupload of a repository I previously have taken down. Please remove or private this repo or I will have to submit a dmca takedown.

**Comment by Minesraft2** [comment]
The point of the repository that this repository is a reupload of was to look nothing like mine so they can get away with taking my scripts. I'm working on taking down their entire fork network and reuploads. I have already sent a DMCA to GitHub.

**Comment by TrollAndHack** [comment]
What About TheRealGliz? glizxer? shenkeYT? And you target me when I have done nothing wrong, trying to share some hard work with my friends.

**Comment by Minesraft2** [comment]
And you're gonna say your hard work when it's stolen from someone who stole them from me?

**Comment by TrollAndHack** [comment]
Anybody could say this.

**Comment by Minesraft2** [comment]
Well if you want to see the dmca against rzx (the person this repo is a reupload of) it's public and can be found here: https://github.com/github/dmca/blob/master/2023/01/2023-01-10-blooklet-hacks.md
As to proof that I'm not just anyone I don't have much other than my reputation in the Blooket community

**Comment by TrollAndHack** [comment]
TheRealGliz said his account was his and that somebody was impersonating them, that might be you.

**Comment by TrollAndHack** [comment]
But idk

**Comment by Minesraft2** [comment]
> TheRealGliz said his account was his and that somebody was impersonating them, that might be you.

Therealgliz was the person impersonation him, but he took the account and remade the login with a temp email

**Comment by TrollAndHack** [comment]
Ok, i see

**Comment by Minesraft2** [comment]
In therealgliz's repo if you go to the gui file you can actually find my name in the credits.

**Comment by Minesraft2** [comment]
https://github.com/therealgliz/blooket-hacks/blob/main/gui.js line 154

**Comment by TrollAndHack** [comment]
Ok, i did copy it, but from somebody else, shenkeYT, but you cannot dcma me because technically I did not break his license rules so you can't do anything.

Also, this was just for my friends, and to have fun.
